# Toolchain tool -- builds a numbered table-of-contents list from
# content/manifest.json (already generated by the time toolchain tools run;
# see CANARY_MANIFEST_PATH in Canary's toolchain guide) and appends it to
# the page's markdown, as a "toc-list" widget fence (see
# widgets/toc-list.html) rather than plain Markdown list syntax -- Canary's
# Markdown renderer parses and discards the leading number on an ordered
# list line (MarkdownRenderer.cs's OlRegex), always rendering a plain <ol>
# numbered 1, 2, 3... by the browser. A widget's own template output is
# real HTML, not re-parsed as Markdown, so it can set each <li>'s real
# "value" instead.
#
# Applied to content/contents/.toolchain.json, the dedicated Contents page
# (page 2, right after the cover -- see its own index.md and .nav.json) --
# add a new top-level content/<slug>/ directory and it shows up here with
# no edit to this page or this script.
#
# Still recurses into "children" to COUNT them -- same depth-first order as
# root-copy/js/notebook.js's flattenNav() and tools/page-number.cs's own
# walk, so a top-level page after a section with subpages still gets its
# real position (e.g. Default File is 9, not 7, because Search's two
# subpages consumed 7 and 8) -- but only prints a row for top-level items.
# A subpage is reached by paging through its own section from the
# notebook, not listed here on its own.
#
# Skips Home ("" path) -- it's the cover, not a section -- and whichever
# entry matches CANARY_ROUTE_PATH, i.e. the page this tool is running on
# itself, so the list never links to itself. Both still consume a
# position; only not printed as a row.
$rows = New-Object System.Collections.Generic.List[string]
$script:position = 0

function Walk($items, $topLevel) {
    foreach ($item in $items) {
        $script:position++
        if ($topLevel -and $item.path -ne "" -and $item.path -ne $env:CANARY_ROUTE_PATH) {
            $rows.Add("  - position: $script:position`n    title: `"$($item.title)`"`n    url: `"/$($item.path)/`"")
        }
        if ($item.children) {
            Walk $item.children $false
        }
    }
}

$source = [Console]::In.ReadToEnd()
$manifest = Get-Content $env:CANARY_MANIFEST_PATH -Raw | ConvertFrom-Json
Walk $manifest.nav $true

$fence = "``````toc-list`nitems:`n" + ($rows -join "`n") + "`n```````n"
$output = $source.TrimEnd() + "`n`n$fence"

[Console]::Out.Write($output)
