# Toolchain tool -- builds a table-of-contents list from content/manifest.json
# (already generated by the time toolchain tools run; see CANARY_MANIFEST_PATH
# in Canary's toolchain guide) and appends it to the page's markdown. Applied
# to content/contents/.toolchain.json, the dedicated Contents page (page 2,
# right after the cover -- see its own index.md and .nav.json) -- add a new
# content/<slug>/ directory and it shows up here with no edit to this page or
# this script.
#
# Skips Home ("" path) -- it's the cover, not a section -- and whichever
# entry matches CANARY_ROUTE_PATH, i.e. the page this tool is running on
# itself, so the list never links to itself.
$source = [Console]::In.ReadToEnd()

$manifest = Get-Content $env:CANARY_MANIFEST_PATH -Raw | ConvertFrom-Json
$links = New-Object System.Collections.Generic.List[string]
foreach ($item in $manifest.nav) {
    if ($item.path -eq "" -or $item.path -eq $env:CANARY_ROUTE_PATH) { continue }
    $links.Add("- [$($item.title)](/$($item.path)/)")
}

$toc = ($links -join "`n")
$output = $source.TrimEnd() + "`n`n$toc`n"

[Console]::Out.Write($output)
